name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App'
        required: true
        type: choice
        options:
          - app1
          - app2
        default: app1
      shouldBuild:
        description: 'Should build'
        required: true
        type: boolean
        default: false
      shouldDeploy:
        description: 'Should deploy'
        required: true
        type: boolean
        default: false
      tag:
        description: 'Tag'
        required: true
        type: string
        default: latest
      profile:
        description: Profile
        type: choice
        options:
          - dev
          - prod
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew ${{ inputs.app }}:build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.app }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:latest