name: Build

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App'
        required: true
        type: string

env:
  APP_NAME: app1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: 'konovalov-maksim/gp-scraper'
          ref: 'gh-actions'

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew ${{ inputs.app }}:build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.APP_NAME }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}:test-gh-actions