name: Deploy image to Docker remote host

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App'
        required: true
        type: choice
        options:
          - app1
          - app2
        default: app1
      tag:
        description: 'Tag'
        required: true
        type: string
        default: latest
      profile:
        description: Profile
        type: choice
        options:
          - dev
          - prod
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Docker-Compose Remote Deployment
        uses: masterjanic/docker-compose-ssh-deployment@master
        with:
          docker_compose_filename: ./app1/docker-compose.yml
          ssh_host: 23.95.218.206
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}